[package]
name = "simpledb"
version = "0.1.0"
authors = ["Peter Hayes <peter.k.hayes@gmail.com>"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"
tokio-proto = "0.1"
nom = "2.1"
